apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - namespace/
 - deployment/
 - service/
        
namespace: kustomize

patches:
 - target:
    kind: Deployment
    name: frontend

   patch: |-
     - op: replace
       path: /spec/replicas
       value: 1
