apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-kutomize
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/omran-zamzam/Guestbook.git
    targetRevision: kustomization/HEAD
    path: dep/manifests/kustomization.yaml
    
    directory:
      recurse: true
      jsonnet: {} 
  destination: 
    server: https://kubernetes.default.svc
    namespace: kustomize

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
