apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
 - ../../manifests/

#images:
# - name: gcr.io/google_samples/gb-frontend
#   newName: nginx
#   newTag: v1


#replicas:
# - name: frontend 
#  count: 1
        
#different way to change replica using patch method

#patches:
# - target:
#    kind: Deployment
#    name: frontend
#   patch: |-
#    - op: replace
#      path: /spec/replicas
#      value: 2

namespace: test8
